### PR TITLE
feat(core): remove component transition

### PR DESCRIPTION
**Pull request by josokinas**
## Purpose

Components to not have transition (animation) to feel more snappy.

## Approach

Remove transition from all components.

## Testing

On Storybook preview.

## Risks

N/A

### CODE REVIEW

**Review by rabelloo — APPROVED** [review]
Sad times 😭 

Hope we can work on animation/transition soon.

**Comment by josokinas** [comment]
> Hope we can work on animation/transition soon.

I personally prefer with no transition/animation - feels faster, animations can only be in needed places like dropdown opening/closing.

**Comment by rabelloo** [comment]
I know, it's all a matter of taste. Hopefully we can have easily customisable transitions, catering to all needs.

**Comment by rabelloo** [comment]
This is good to merge. Not sure this is `refactor`, probably either `fix` or `feat`, but it's fine.

**Comment by josokinas** [comment]
> This is good to merge. Not sure this is `refactor`, probably either `fix` or `feat`, but it's fine.

I will only merge after acceptance testing by @Subcide.

**Comment by josokinas** [comment]
Renamed (and will be commited as) to `feat(core): remove component transition` as per [@rabelloo suggestion](https://github.com/onfido/castor/pull/31#issuecomment-737315315).

**Comment by Subcide** [comment]
Sorry, I missed this email, still getting used to GitHub and it's VERY noisy to start with.  Where can I find a link to test? The link further up the comments on Surge had animations still.

**Comment by josokinas** [comment]
> The link further up the comments on Surge had animations still.

Indeed it does - that's really strange! I suspect something's not right with the preview.

I will merge this now, so please @Subcide use main Storybook for acceptance testing, and later will take a look at why previews are not working as they should.

**Pull request merged**
