### PR TITLE
docs: migrate to CSF3

### PR DESCRIPTION
**Pull request by rabelloo**
## Purpose

Migrate from CSF2 to [CSF3](https://storybook.js.org/blog/component-story-format-3-0/)

## Approach

Follow [Storybook's guide](https://storybook.js.org/blog/component-story-format-3-0/)

## Testing

Storybook should continue to display the same thing

## Risks

New format is a bit more verbose for a small amount of use cases, but better for most and also enables [interaction testing](https://storybook.js.org/blog/interaction-testing-sneak-peek/)

### CODE REVIEW

**Review by josokinas — APPROVED** [review]
Blindly approving this - as long as all still functions 😏

**Comment by rabelloo** [comment]
I'd appreciate it if you could take a look at one change example, such as `button.stories.tsx`, just to see what's the new API like.

In my opinion it makes the regular matrices we have for individual properties much cleaner (with our helper), but it makes the "all combinations" stories a bit more verbose

**Comment by josokinas** [comment]
All good, I don't mind either - it's only a matter of getting used to.

BTW, Docs tab is not working, is this expected?

**Comment by rabelloo** [comment]
Yes, it requires the fix in https://github.com/onfido/castor/pull/1180

**Pull request merged**
